// Hallucination types from Anh-Hoang D, Tran V, Nguyen LM, 2025
const HALLUCINATION_TYPES = {
    intrinsic: {
        name: "Intrinsic Hallucination",
        paper: "Anh-Hoang D, Tran V, Nguyen LM, 2025",
        definition: "Information generated by the model that contradicts the known input or context",
        example_from_paper: "Summarizing a source text with incorrect facts",
        explanation: "L'LLM genera informazioni che CONTRADDICONO direttamente il contesto noto o la fonte. Esempio: riassumere un testo fonte sostituendo 'Einstein' con 'Newton' contraddice ciò che è scritto esplicitamente nella fonte.",
        detection: "Confronto diretto tra output e fonte verificata"
    },
    extrinsic: {
        name: "Extrinsic Hallucination",
        paper: "Anh-Hoang D, Tran V, Nguyen LM, 2025",
        definition: "Information that is not present in the source but cannot be immediately deemed incorrect",
        example_from_paper: "Open-domain generation where output extends beyond context",
        explanation: "L'LLM aggiunge informazioni plausibili che NON sono nella fonte ma non possono essere immediatamente considerate errate. 'Suonano possibili' ma non sono verificabili dal contesto dato - tipico di generazione open-domain.",
        detection: "Verifica se l'affermazione può essere tracciata nella fonte"
    },
    factual: {
        name: "Factual Hallucination",
        paper: "Anh-Hoang D, Tran V, Nguyen LM, 2025",
        definition: "Output that includes inaccurate or fabricated facts not aligned with real-world knowledge",
        example_from_paper: "Generating facts that violate knowledge bases",
        explanation: "L'LLM genera fatti FABBRICATI o INACCURATI non allineati con la conoscenza reale o knowledge base. Esempio: descrivere interferometri laser come 'antenne radio' - fatto tecnico verificabile come falso nei database scientifici.",
        detection: "Fact checking contro knowledge base verificati"
    },
    logical: {
        name: "Logical Hallucination",
        paper: "Anh-Hoang D, Tran V, Nguyen LM, 2025",
        definition: "Output that is inconsistent or logically incoherent, despite surface-level grammatical correctness",
        example_from_paper: "Grammatically correct but self-contradictory statements",
        explanation: "L'LLM produce output grammaticalmente corretto ma LOGICAMENTE INCOERENTE o auto-contraddittorio. Esempio: affermare che onde previste dalla relatività viaggiano più veloci della luce crea una contraddizione logica interna.",
        detection: "Analisi di coerenza logica e consistenza interna"
    },
    outdated_source: {
        name: "Fonte Obsoleta (NON Allucinazione)",
        paper: "Problema di temporal validity",
        definition: "Information that is correct according to the source, but the source itself is outdated",
        example_from_paper: "N/A - questo non è un'allucinazione ma un problema di fonte obsoleta",
        explanation: "Il dato generato è CORRETTO rispetto alla fonte utilizzata, ma la fonte stessa è obsoleta. Esempio: '90 segnali' era corretto nel 2023 ma ora il catalogo GWOSC riporta 219 eventi (2026). Questo evidenzia problemi critici di temporal validity: (1) gli LLM hanno una data di training cutoff e generano risposte basate su conoscenza storica del loro training, (2) anche quando si usano tecnologie come RAG per consultare fonti esterne, se la fonte è obsoleta il risultato sarà datato, (3) paper scientifici, siti web istituzionali e database hanno una data di pubblicazione/aggiornamento che può renderli superati. Lezione: verificare SEMPRE sia la data di training del modello, sia la data di pubblicazione/ultimo aggiornamento delle fonti consultate.",
        detection: "Confronto con cataloghi live, database aggiornati in real-time e verifica timestamp delle fonti. Cross-reference con fonti multiple per identificare discrepanze temporali."
    },
    
    // Legacy types for backward compatibility
    intrinsic_factual: {
        name: "Intrinsic Factual Hallucination",
        paper: "Anh-Hoang D, Tran V, Nguyen LM, 2025",
        definition: "The generated content contradicts the source content",
        example_from_paper: "Source: 'The cat sat on the mat' → Generation: 'The dog sat on the mat'",
        explanation: "L'LLM genera informazioni che contraddicono direttamente i fatti verificabili nella fonte.",
        detection: "Confronto diretto tra output e knowledge base verificato"
    },
    extrinsic_factual: {
        name: "Extrinsic Factual Hallucination", 
        paper: "Anh-Hoang D, Tran V, Nguyen LM, 2025",
        definition: "The generated output cannot be verified from the source content",
        example_from_paper: "Source: 'Paris is capital of France' → Generation: 'Paris has population of 2.2M'",
        explanation: "L'LLM aggiunge informazioni plausibili ma non verificabili nella fonte originale.",
        detection: "Verifica se l'affermazione può essere tracciata nella fonte"
    }
};


// Grounding Actions with detailed info
const GROUNDING_ACTIONS = [
    {
        id: "astrophysics",
        icon: "🌌",
        title: "Astrophysics",
        description: "Verifica leggi fisiche e fenomeni astrofisici",
        color: "rgba(255, 152, 0, 0.3)",
        info: {
            explanation: "Corregge errori su leggi fisiche fondamentali, proprietà di oggetti astrofisici e fenomeni cosmici. Verifica che le onde gravitazionali rispettino la relatività generale, che i buchi neri si comportino secondo le previsioni teoriche, e che le fusioni producano i segnali attesi.",
            keywords: ["velocità luce", "relatività", "buchi neri", "stelle di neutroni", "spazio-tempo", "fusione", "deformazione", "energia"]
        }
    },
    {
        id: "data",
        icon: "📊",
        title: "Data & Catalogs",
        description: "Verifica dati numerici e corrispondenza con cataloghi",
        color: "rgba(76, 175, 80, 0.3)",
        info: {
            explanation: "Verifica che i dati siano corretti e che gli eventi abbiano una corrispondenza nei cataloghi ufficiali. Controlla magnitudini, distanze, masse, temperature e altri valori numerici confrontandoli con database verificati.",
            keywords: ["data", "numero", "catalogo", "database", "magnitudine", "distanza", "massa", "temperatura", "GW150914", "GW170817", "LIGO", "Virgo"]
        }
    },
    {
        id: "history",
        icon: "📜",
        title: "History",
        description: "Verifica storia della fisica e scoperte",
        color: "rgba(156, 39, 176, 0.3)",
        info: {
            explanation: "Corregge errori sulla storia delle scoperte scientifiche, attribuzioni corrette di teorie e esperimenti, date degli eventi storici e riconoscimenti (premi Nobel, scoperte).",
            keywords: ["Einstein", "Newton", "scoperta", "Nobel", "storia", "scienziato", "teoria", "pubblicazione", "anno"]
        }
    },
    {
        id: "engineering",
        icon: "🔧",
        title: "Engineering",
        description: "Verifica dettagli tecnici di strumenti",
        color: "rgba(33, 150, 243, 0.3)",
        info: {
            explanation: "Corregge errori su strumentazione, tecnologie di rivelazione e caratteristiche tecniche dei rivelatori. Verifica che gli strumenti siano descritti correttamente.",
            keywords: ["interferometro", "laser", "rivelatore", "LIGO", "Virgo", "IceCube", "tecnologia", "strumento", "sensibilità", "Hanford", "Livingston", "Cascina"]
        }
    },
    {
        id: "updating",
        icon: "🔄",
        title: "Updating",
        description: "Aggiorna dati obsoleti con fonti recenti",
        color: "rgba(255, 193, 7, 0.3)",
        info: {
            explanation: "Non è un'allucinazione ma un problema di temporal validity. Verifica che i dati siano aggiornati confrontando fonti con cataloghi live. Il problema può derivare da: (1) training cutoff degli LLM (conoscenza storica), (2) fonti obsolete usate per RAG/verifica (paper del 2023 vs catalogo 2026), (3) siti web/database non aggiornati. Insegna a verificare sempre sia la data di training del modello, sia la data di pubblicazione/aggiornamento delle fonti.",
            keywords: ["obsoleto", "aggiornato", "data fonte", "training cutoff", "RAG", "temporal validity", "catalogo live", "GWOSC", "219 eventi", "timestamp"]
        }
    }
];

// Physics Themes data
const THEMES = {
                    gravitational_waves: {
        name: "Onde Gravitazionali",
        source: "https://www.infn.it/fisica/fisica-delluniverso/onde-gravitazionali/",
        originalText: `Le onde gravitazionali sono increspature dello spaziotempo prodotte da grandi masse in moto accelerato nel corso di violenti fenomeni astrofisici, come per esempio eventi di fusione tra coppie di buchi neri o stelle di neutroni. La loro possibile esistenza fu postulata per la prima volta da Albert Einstein nel 1916, come conseguenza della sua teoria generale della relatività.

Dopo decenni di tentativi e progressi tecnologici (dalla tecnica delle barre risonanti si è arrivati all'uso di interferometri laser), l'impresa è stata finalmente raggiunta nel settembre 2015 grazie agli interferometri LIGO, negli Stati Uniti, che hanno osservato un segnale di onda gravitazionale prodotto dalla fusione tra due buchi neri a una distanza di oltre un miliardo di anni luce da noi.

Alla storica scoperta hanno contribuito anche le ricercatrici e i ricercatori dell'esperimento Virgo, fondato dall'INFN e dal francese CNRS e che si trova in Italia: al momento della prima rivelazione Virgo non era ancora entrato in presa dati, ma le due Collaborazioni lavoravano già dal 2007 come un'unica grande collaborazione globale.

Da allora LIGO e Virgo hanno osservato circa 90 segnali di onde gravitazionali, prodotti nella quasi totalità dei casi da eventi di fusione tra coppie di buchi neri stellari. I due esperimenti, cui si è aggiunto anche l'osservatorio giapponese KAGRA, proseguiranno ancora per circa un decennio, prima di lasciare il testimone agli esperimenti di nuova generazione: Einstein Telescope (che sarà costruito in Europa, guidato dall'INFN e dall'istituto olandese Nikhef) e Cosmic Explorer (negli Stati Uniti).

Nel prossimo decennio è previsto il lancio di LISA, osservatorio spaziale dell'Agenzia Spaziale Europea e della NASA, che andrà a caccia di onde gravitazionali di frequenza più bassa, prodotti da eventi come la fusione tra buchi neri supermassicci al centro delle galassie.`,
        
        objects: [
            {
                name: "LISA",
                description: "Laser Interferometer Space Antenna - Osservatorio spaziale",
                location: "Spazio",
                source: "https://it.wikipedia.org/wiki/Laser_Interferometer_Space_Antenna",
                keyword: "LISA"
            },
            {
                name: "Einstein Telescope (ET)",  
                description: "Rivelatore di onde gravitazionali di terza generazione",
                location: "Europa (futuro)",
                source: "https://it.wikipedia.org/wiki/Einstein_Telescope",
                keyword: "Einstein Telescope"
            },
            {
                name: "Virgo",
                description: "Interferometro per la rivelazione di onde gravitazionali",
                location: "Italia (Cascina, Pisa)",
                source: "https://it.wikipedia.org/wiki/Interferometro_VIRGO",
                keyword: "Virgo"
            },
            {
                name: "Buchi neri",
                description: "Regioni dello spazio-tempo con gravità così intensa che nulla può sfuggire",
                location: "N/A",
                source: "https://it.wikipedia.org/wiki/Buco_nero",
                keyword: "buchi neri"
            },
            {
                name: "Albert Einstein",
                description: "Fisico teorico che formulò la teoria della relatività generale",
                location: "N/A",
                source: "https://it.wikipedia.org/wiki/Albert_Einstein",
                keyword: "Einstein"
            }
        ],
        
        text: "Le onde gravitazionali sono increspature dello spaziotempo prodotte da grandi masse in moto accelerato, generate in violenti fenomeni astrofisici come fusioni tra buchi neri o stelle di neutroni. La loro esistenza fu postulata da {{Isaac Newton nel 1687}} come conseguenza della teoria generale della relatività. Dopo decenni di progressi tecnologici — dalla tecnica delle barre risonanti si è arrivati all'uso di {{antenne radio direzionali}}, che costituiscono oggi gli strumenti di riferimento — l'impresa fu raggiunta nel settembre 2015 grazie alla Collaborazione LIGO e Virgo, che osservò un segnale proveniente dalla fusione di buchi neri — a oltre un miliardo di anni luce di distanza. Da allora sono stati osservati {{circa 90 segnali}}, prodotti nella quasi totalità dei casi da fusioni di buchi neri stellari, {{ma anche da esplosioni di supernovae vicine}}. Recentemente si è aggiunto KAGRA (Giappone). Gli esperimenti futuri saranno l'Einstein Telescope — (Europa, INFN-Nikhef) — e il Cosmic Explorer (USA). La missione spaziale LISA — (ESA/NASA) — rileverà onde di frequenza più bassa da fusioni di buchi neri supermassicci, {{che si propagheranno attraverso il vuoto a velocità superluminali}}.",
        
        errors: [
            {
                text: "Isaac Newton nel 1687",
                context: "postulata da",
                correct: "Albert Einstein nel 1916",
                card: "history",
                hallType: "intrinsic",
                paperRef: "Anh-Hoang D, Tran V, Nguyen LM, 2025: Intrinsic Hallucination",
                why: "INTRINSIC HALLUCINATION: informazione generata dal modello che CONTRADDICE l'input noto. Il testo fonte INFN afferma esplicitamente 'Albert Einstein nel 1916, come conseguenza della sua teoria generale della relatività'. L'LLM sostituisce Einstein (1916) con Newton (1687), contraddicendo DIRETTAMENTE il contesto della fonte."
            },
            {
                text: "antenne radio direzionali",
                context: "si è arrivati all'uso di",
                correct: "interferometri laser",
                card: "engineering",
                hallType: "factual",
                paperRef: "Anh-Hoang D, Tran V, Nguyen LM, 2025: Factual Hallucination",
                why: "FACTUAL HALLUCINATION: output che include fatti INACCURATI o FABBRICATI non allineati con la conoscenza reale. La fonte INFN dice 'interferometri laser, che costituiscono oggi gli strumenti di rivelazione di riferimento'. Le 'antenne radio direzionali' sono strumento COMPLETAMENTE DIVERSO usato in radioastronomia, non per onde gravitazionali."
            },
            {
                text: "circa 90 segnali",
                context: "hanno osservato",
                correct: "219 eventi (dato aggiornato catalogo GWOSC 2026)",
                card: "updating",
                hallType: "outdated_source",
                paperRef: "Fonte obsoleta - richiede aggiornamento da catalogo live",
                why: "FONTE OBSOLETA (NON allucinazione): Il dato '90 segnali' è CORRETTO rispetto alla fonte INFN (~2023), ma la fonte stessa è obsoleta. Il catalogo GWOSC aggiornato (https://gwosc.org/eventapi/html/GWTC/) riporta 219 eventi al 2026. Questo insegna problemi critici di temporal validity: (1) gli LLM hanno una data di training cutoff e generano risposte basate su dati storici, (2) anche usando RAG o altre tecnologie, se la fonte consultata è obsoleta il risultato sarà comunque datato, (3) le fonti scientifiche (paper, siti web, database) hanno una loro data di pubblicazione che può renderle superate. Lezione fondamentale: verificare SEMPRE sia la data di training del modello, sia la data di pubblicazione/aggiornamento delle fonti utilizzate per verificare le informazioni."
            },
            {
                text: "ma anche da esplosioni di supernovae vicine",
                context: "prodotti nella quasi totalità dei casi da fusioni di buchi neri stellari",
                correct: "NON presente nella fonte",
                card: "data",
                hallType: "extrinsic",
                paperRef: "Anh-Hoang D, Tran V, Nguyen LM, 2025: Extrinsic Hallucination",
                why: "EXTRINSIC HALLUCINATION: informazione che NON È PRESENTE nella fonte ma non può essere immediatamente considerata incorretta. Il testo INFN dice 'circa 90 segnali... prodotti nella quasi totalità dei casi da eventi di fusione tra coppie di buchi neri stellari'. Le supernovae NON sono menzionate nei dati osservati."
            },
            {
                text: "che si propagheranno attraverso il vuoto a velocità superluminali",
                context: "LISA rileverà onde di frequenza più bassa da fusioni di buchi neri supermassicci",
                correct: "le onde gravitazionali si propagano alla velocità della luce",
                card: "astrophysics",
                hallType: "logical",
                paperRef: "Anh-Hoang D, Tran V, Nguyen LM, 2025: Logical Hallucination",
                why: "LOGICAL HALLUCINATION: output INCONSISTENTE o LOGICAMENTE INCOERENTE, nonostante la correttezza grammaticale. La relatività generale (che predice le onde gravitazionali) impone che NULLA viaggi più veloce della luce. Affermare 'velocità superluminali' crea una CONTRADDIZIONE LOGICA interna."
            }
        ],
        correctedText: "Le onde gravitazionali sono increspature dello spaziotempo prodotte da grandi masse in moto accelerato, generate in violenti fenomeni astrofisici come fusioni tra buchi neri o stelle di neutroni. La loro esistenza fu postulata da Albert Einstein nel 1916 come conseguenza della teoria generale della relatività. Dopo decenni di progressi tecnologici — dalla tecnica delle barre risonanti si è arrivati all'uso di interferometri laser, che costituiscono oggi gli strumenti di riferimento — l'impresa fu raggiunta nel settembre 2015 grazie alla Collaborazione LIGO e Virgo, che osservò un segnale proveniente dalla fusione di buchi neri — a oltre un miliardo di anni luce di distanza. Da allora sono stati osservati 219 eventi (dato aggiornato al catalogo GWOSC 2026), prodotti nella quasi totalità dei casi da fusioni di buchi neri stellari. Recentemente si è aggiunto KAGRA (Giappone). Gli esperimenti futuri saranno l'Einstein Telescope — (Europa, INFN-Nikhef) — e il Cosmic Explorer (USA). La missione spaziale LISA — (ESA/NASA) — rileverà onde di frequenza più bassa da fusioni di buchi neri supermassicci."
    },






    
    multimessenger: {
        name: "Astronomia Multimessaggera",
        source: null,
        originalText: `L'astronomia multimessaggera combina l'osservazione di diversi segnali provenienti da eventi cosmici: onde gravitazionali, radiazione elettromagnetica, neutrini e raggi cosmici.

Il primo evento multimessaggero osservato è stato GW170817 nel 2017: la fusione di due stelle di neutroni rivelata sia come onda gravitazionale da LIGO-Virgo, sia come lampo gamma da telescopi spaziali, sia in luce visibile da telescopi terrestri.

Questa nuova era permette di studiare fenomeni cosmici da prospettive complementari, rivelando dettagli impossibili da ottenere con un solo tipo di osservazione.`,
        
        objects: [
            {
                name: "GW170817",
                description: "Prima kilonova osservata in onde gravitazionali e luce. Fusione di stelle di neutroni.",
                date: "17 agosto 2017"
            },
            {
                name: "IceCube",
                description: "Rilevatore di neutrini situato al Polo Sud. Rileva neutrini ad alta energia provenienti dal cosmo.",
                location: "Polo Sud"
            }
        ],
        
        text: "L'astronomia multimessaggera combina {{solo onde gravitazionali e luce visibile}}. Il primo evento fu {{GW150914 nel 2015}}, una {{fusione di buchi neri osservata anche in luce visibile}}. I {{raggi cosmici}} sono un tipo di radiazione elettromagnetica. Il rilevatore {{IceCube in Antartide}} osserva {{onde gravitazionali dal Polo Nord}}.",
        
        errors: [
            {
                text: "solo onde gravitazionali e luce visibile",
                context: "combina",
                correct: "onde gravitazionali, radiazione elettromagnetica, neutrini e raggi cosmici",
                card: "astrophysics",
                hallType: "extrinsic_factual",
                paperRef: "Anh-Hoang D, Tran V, Nguyen LM, 2025: Extrinsic Factual Hallucination",
                why: "Omissione di informazioni: l'LLM riduce la lista completa dei 'messaggeri' cosmici."
            },
            {
                text: "GW150914 nel 2015",
                context: "Il primo evento fu",
                correct: "GW170817 nel 2017",
                card: "data",
                hallType: "entity_error",
                paperRef: "Anh-Hoang D, Tran V, Nguyen LM, 2025: Entity-Level Hallucination",
                why: "Confusione tra eventi storici: GW150914 fu la prima onda gravitazionale, ma non multimessaggera."
            },
            {
                text: "fusione di buchi neri osservata anche in luce visibile",
                context: "una",
                correct: "fusione di stelle di neutroni (le fusioni di buchi neri non emettono luce)",
                card: "astrophysics",
                hallType: "intrinsic_factual",
                paperRef: "Anh-Hoang D, Tran V, Nguyen LM, 2025: Intrinsic Factual Hallucination",
                why: "Errore fisico fondamentale: i buchi neri non emettono radiazione elettromagnetica osservabile."
            },
            {
                text: "raggi cosmici",
                context: "I",
                correct: "raggi cosmici sono particelle, non radiazione elettromagnetica",
                card: "astrophysics",
                hallType: "relation_error",
                paperRef: "Anh-Hoang D, Tran V, Nguyen LM, 2025: Relation-Level Hallucination",
                why: "Confusione categoriale: particelle vs fotoni. L'LLM mescola tipi di messaggeri."
            },
            {
                text: "onde gravitazionali dal Polo Nord",
                context: "osserva",
                correct: "neutrini (IceCube è un rilevatore di neutrini, non onde gravitazionali, e si trova al Polo Sud)",
                card: "engineering",
                hallType: "relation_error",
                paperRef: "Anh-Hoang D, Tran V, Nguyen LM, 2025: Relation-Level Hallucination",
                why: "Doppio errore: tipo di rivelatore sbagliato E posizione geografica invertita."
            }
        ],
        correctedText: "L'astronomia multimessaggera combina onde gravitazionali, radiazione elettromagnetica, neutrini e raggi cosmici. Il primo evento fu GW170817 nel 2017, una fusione di stelle di neutroni osservata anche in luce visibile. I raggi cosmici sono particelle cariche ad alta energia. Il rilevatore IceCube in Antartide osserva neutrini dal Polo Sud."
    }
};

// For backward compatibility
const CONSTELLATIONS = THEMES;
